@include('backEnd.mastering.includes.headAssets')
@include('backEnd.mastering.includes.navbar')
@include('backEnd.mastering.includes.aside')
@yield('backEndBody')
@include('backEnd.mastering.includes.footer')
@include('backEnd.mastering.includes.bottomAssets')
